# -*- coding: utf-8 -*-
"""thousand_new_orders.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1od49SLi0CslolRjnY3xl7XN86t7DQhBM
"""

import random
from datetime import datetime, timedelta
import csv
import math

def round_up(n, decimals = 0):
  multiplier = 10 ** decimals
  return math.ceil(n*multiplier) / multiplier

entree_orders = random.randint(1,6)
sides_orders = random.randint(1,3)
beverage_orders = random.randint(1,4)
desserts_orders = random.randint(1,1)
ingred_orders = random.randint(1,2)

entrees = ['E1','E2', 'E3', 'E4', 'E5', 'E6', 'E7']
sides = ['S1', 'S2', 'S3', 'S4']
beve = ['B1', 'B2', 'B3', 'B4', 'B5']
desserts = ['D1', 'D2']
ingredients = ['I1', 'I2','I3', 'I4','I5', 'I6','I7', 'I8','I9', 'I10','I11', 'I12',
'I13', 'I14','I15', 'I16','I7', 'I18','I19', 'I20','I21', 'I22','I23', 'I24']

hold = ""
random_entrees = []
for i in range(0, 1000):
  for j in range(0, entree_orders): 
    random_entree_index = random.randint(0,len(entrees)-1)
    hold += entrees[random_entree_index]
    if(j != entree_orders-1):
      hold += ":"
  for k in range(0, ingred_orders):
    random_ingredient_index = random.randint(0,len(ingredients)-1)
    hold += ";" + ingredients[random_ingredient_index]
  random_entrees.append(hold)   
  hold = ""

hold = ""
random_sides = []
for i in range(0, 1000):
  for j in range(0, sides_orders):
    random_side_index = random.randint(0, len(sides)-1)
    hold += sides[random_side_index]
    if(j != sides_orders-1):
      hold += ":"
  for k in range(0, ingred_orders):
    random_ingredient_index = random.randint(0,len(ingredients)-1)
    hold += ";" + ingredients[random_ingredient_index]
  random_sides.append(hold)   
  hold = ""

hold = ""
random_beverages = []
for i in range(0, 1000):
  for j in range(0, beverage_orders):
    random_beverage_orders = random.randint(0, len(beve)-1)
    hold += beve[random_beverage_orders]
    if(j != beverage_orders-1):
      hold += ":"
  for k in range(0, ingred_orders):
    random_ingredient_index = random.randint(0,len(ingredients)-1)
    hold += ";" + ingredients[random_ingredient_index]
  random_beverages.append(hold)   
  hold = ""

hold = ""
random_dessert = []
for i in range(0, 1000):
  for j in range(0, desserts_orders):
    random_dessert_orders = random.randint(0, len(desserts)-1)
    hold += desserts[random_dessert_orders]
    if(j != desserts_orders-1):
      hold += ":"
  for k in range(0, ingred_orders):
    random_ingredient_index = random.randint(0,len(ingredients)-1)
    hold += ";" + ingredients[random_ingredient_index]
  random_dessert.append(hold)   
  hold = ""

no_items = entree_orders + sides_orders + beverage_orders + desserts_orders
id = 1000000
id = int(id)
customer_id_random_list = []
for i in range(0, 1000):
  customer_id_random_list.append(random.randint(0,500000))

random_dates = []

min_year=2020
max_year=2020

start = datetime(min_year, 1, 1, 00)
years = max_year - min_year+1
end = start + timedelta(days=365 * years)

for i in range(1000):
    random_date = start + (end - start) * random.random()
    hold = ""
    hold += random_date.strftime("%Y") + "-" + random_date.strftime("%m") + "-" + random_date.strftime("%d")
    random_dates.append(hold)

total_E1 = 0
total_E2 = 0
total_E3 = 0
total_E4 = 0
total_E5 = 0
total_E6 = 0
total_E7 = 0

total_S1 = 0
total_S2 = 0
total_S3 = 0
total_S4 = 0

total_B1 = 0
total_B2 = 0
total_B3 = 0
total_B4 = 0
total_B5 = 0

total_I1 = 0
total_I2 = 0
total_I3 = 0
total_I4 = 0
total_I5 = 0
total_I6 = 0
total_I7 = 0
total_I8 = 0
total_I9 = 0
total_I10 = 0
total_I11 = 0
total_I12 = 0
total_I13 = 0
total_I14 = 0
total_I15 = 0
total_I16 = 0
total_I17 = 0
total_I18 = 0
total_I19 = 0
total_I20 = 0
total_I21 = 0
total_I22 = 0
total_I23 = 0
total_I24 = 0

total_D1 = 0
total_D2 = 0

total_cost_list = []
print()
for x in random_entrees:
  total_E1 = x.count("E1")
  total_E2 = x.count("E2")
  total_E3 = x.count("E3")
  total_E4 = x.count("E4")
  total_E5 = x.count("E5")
  total_E6 = x.count("E6")
  total_E7 = x.count("E7")
  total_S1 = x.count("S1")
  total_S2 = x.count("S2")
  total_S3 = x.count("S3")
  total_S4 = x.count("S4")
  total_B1 = x.count("B1")
  total_B2 = x.count("B2")
  total_B3 = x.count("B3")
  total_B4 = x.count("B4")
  total_B5 = x.count("B5")
  total_I1 = x.count("I1")
  total_I2 = x.count("I2")
  total_I3 = x.count("I3")
  total_I4 = x.count("I4")
  total_I5 = x.count("I5")
  total_I6 = x.count("I6")
  total_I7 = x.count("I7")
  total_I8 = x.count("I8")
  total_I9 = x.count("I9")
  total_I10 = x.count("I10")
  total_I11 = x.count("I11")
  total_I12 = x.count("I12")
  total_I13 = x.count("I13")
  total_I14 = x.count("I14")
  total_I15 = x.count("I15")
  total_I16 = x.count("I16")
  total_I17 = x.count("I17")
  total_I8 = x.count("I18")
  total_I19 = x.count("I19")
  total_I20 = x.count("I20")
  total_I21 = x.count("I21")
  total_I22 = x.count("I22")
  total_I23 = x.count("I23")
  total_I24 = x.count("I24")
  total_D1 = x.count("D1")
  total_D2 = x.count("D2")
  total_cost = (total_E1 * 3.75) + (total_E2 * 3.99) + (total_E3 * 3.85)
  total_cost += (total_E4 * 5.39) + (total_E5 * 2.69) + (total_E6 * 3.85)
  total_cost += (total_E7 * 3.49) + (total_S1 * 1.69) +  (total_S2 * 1.95) 
  total_cost += (total_S3 * 2.25) + (total_S4 * 1.99) + (total_B1 * 1.85)  
  total_cost += (total_B2 * 1.49) + (total_B3 * 1.75) +  (total_B4 * 2.09) 
  total_cost += (total_B5 * 2.09) + (total_D1 * 1.35) + (total_D2 * 3.35)
  total_cost += (total_I1 * 0.5) + (total_I2 * 1.7) + (total_I3* 1.1) 
  total_cost += (total_I4 * 0.3) + (total_I5 * 0.3) +  (total_I6 * 0.3)
  total_cost += (total_I7 * 1.5) +  (total_I8 * 0.2) + (total_I9 * 0.2)  
  total_cost_list.append(round_up(total_cost, 2))
  total_cost=0

f = open('1k_new', 'w')
writer = csv.writer(f, delimiter = ",")

for i in range(0, 1000):
  data = [id, [customer_id_random_list[i]], [random_dates[i]], [total_cost_list[i]], no_items, [random_entrees[i]], [random_sides[i]], [random_beverages[i]], [random_dessert[i]]]
  writer.writerow(data)
  id += 1

